### ISSUE TITLE
com.platone.clean:core包无法下载

### ISSUE THREAD

**Issue by zhaowei-laster** [Metisnetwork/Moirae-Manager-Platform#2]
请问是否可以分享一下com.platone.client:core:0.1.6.0-SNAPSHOT 包

**Comment by chenxiaodai** [comment]
我们准备修改下引用实现，换掉该引用，修订后会会知您

**Comment by chenxiaodai** [comment]
在下面 commit 解决
https://github.com/Metisnetwork/Moirae-Manager-Platform/commit/d5ccc99b3ef719b484a882743d3cc5101ada0946
